# This file is generated by an ERB template. Do not edit it directly.

  resource "aws_ebs_volume" "data_a" {
  availability_zone = "${var.region}a"
  count             = "${contains(keys(var.subnet_ids), "a") ? var.data_nodes_per_subnet : 0}"
  size              = "${var.data_storage_gb}"
  type              = "${var.storage_type}"

  tags = {
    Name = "${format("elasticsearch-data_a-data-%s-%d", var.cluster_name, count.index + 1)}"
    cluster = "${var.cluster_name}"
  }
}

resource "aws_volume_attachment" "data_a" {
  device_name = "/dev/xvd${var.device_names["data"]}"
  count       = "${contains(keys(var.subnet_ids), "a") ? var.data_nodes_per_subnet : 0}"
  volume_id   = "${element(aws_ebs_volume.data_a.*.id, count.index)}"
  instance_id = "${element(aws_instance.data_a.*.id, (count.index / var.data_nodes_per_subnet))}"
}
  resource "aws_ebs_volume" "logs_a" {
  availability_zone = "${var.region}a"
  count             = "${contains(keys(var.subnet_ids), "a") ? var.data_nodes_per_subnet : 0}"
  size              = "${var.logs_storage_gb}"
  type              = "${var.storage_type}"

  tags = {
    Name = "${format("elasticsearch-data_a-logs-%s-%d", var.cluster_name, count.index + 1)}"
    cluster = "${var.cluster_name}"
  }
}

resource "aws_volume_attachment" "logs_a" {
  device_name = "/dev/xvd${var.device_names["logs"]}"
  count       = "${contains(keys(var.subnet_ids), "a") ? var.data_nodes_per_subnet : 0}"
  volume_id   = "${element(aws_ebs_volume.logs_a.*.id, count.index)}"
  instance_id = "${element(aws_instance.data_a.*.id, (count.index / var.data_nodes_per_subnet))}"
}
    resource "aws_ebs_volume" "data_b" {
  availability_zone = "${var.region}b"
  count             = "${contains(keys(var.subnet_ids), "b") ? var.data_nodes_per_subnet : 0}"
  size              = "${var.data_storage_gb}"
  type              = "${var.storage_type}"

  tags = {
    Name = "${format("elasticsearch-data_b-data-%s-%d", var.cluster_name, count.index + 1)}"
    cluster = "${var.cluster_name}"
  }
}

resource "aws_volume_attachment" "data_b" {
  device_name = "/dev/xvd${var.device_names["data"]}"
  count       = "${contains(keys(var.subnet_ids), "b") ? var.data_nodes_per_subnet : 0}"
  volume_id   = "${element(aws_ebs_volume.data_b.*.id, count.index)}"
  instance_id = "${element(aws_instance.data_b.*.id, (count.index / var.data_nodes_per_subnet))}"
}
  resource "aws_ebs_volume" "logs_b" {
  availability_zone = "${var.region}b"
  count             = "${contains(keys(var.subnet_ids), "b") ? var.data_nodes_per_subnet : 0}"
  size              = "${var.logs_storage_gb}"
  type              = "${var.storage_type}"

  tags = {
    Name = "${format("elasticsearch-data_b-logs-%s-%d", var.cluster_name, count.index + 1)}"
    cluster = "${var.cluster_name}"
  }
}

resource "aws_volume_attachment" "logs_b" {
  device_name = "/dev/xvd${var.device_names["logs"]}"
  count       = "${contains(keys(var.subnet_ids), "b") ? var.data_nodes_per_subnet : 0}"
  volume_id   = "${element(aws_ebs_volume.logs_b.*.id, count.index)}"
  instance_id = "${element(aws_instance.data_b.*.id, (count.index / var.data_nodes_per_subnet))}"
}
    resource "aws_ebs_volume" "data_c" {
  availability_zone = "${var.region}c"
  count             = "${contains(keys(var.subnet_ids), "c") ? var.data_nodes_per_subnet : 0}"
  size              = "${var.data_storage_gb}"
  type              = "${var.storage_type}"

  tags = {
    Name = "${format("elasticsearch-data_c-data-%s-%d", var.cluster_name, count.index + 1)}"
    cluster = "${var.cluster_name}"
  }
}

resource "aws_volume_attachment" "data_c" {
  device_name = "/dev/xvd${var.device_names["data"]}"
  count       = "${contains(keys(var.subnet_ids), "c") ? var.data_nodes_per_subnet : 0}"
  volume_id   = "${element(aws_ebs_volume.data_c.*.id, count.index)}"
  instance_id = "${element(aws_instance.data_c.*.id, (count.index / var.data_nodes_per_subnet))}"
}
  resource "aws_ebs_volume" "logs_c" {
  availability_zone = "${var.region}c"
  count             = "${contains(keys(var.subnet_ids), "c") ? var.data_nodes_per_subnet : 0}"
  size              = "${var.logs_storage_gb}"
  type              = "${var.storage_type}"

  tags = {
    Name = "${format("elasticsearch-data_c-logs-%s-%d", var.cluster_name, count.index + 1)}"
    cluster = "${var.cluster_name}"
  }
}

resource "aws_volume_attachment" "logs_c" {
  device_name = "/dev/xvd${var.device_names["logs"]}"
  count       = "${contains(keys(var.subnet_ids), "c") ? var.data_nodes_per_subnet : 0}"
  volume_id   = "${element(aws_ebs_volume.logs_c.*.id, count.index)}"
  instance_id = "${element(aws_instance.data_c.*.id, (count.index / var.data_nodes_per_subnet))}"
}
    resource "aws_ebs_volume" "data_d" {
  availability_zone = "${var.region}d"
  count             = "${contains(keys(var.subnet_ids), "d") ? var.data_nodes_per_subnet : 0}"
  size              = "${var.data_storage_gb}"
  type              = "${var.storage_type}"

  tags = {
    Name = "${format("elasticsearch-data_d-data-%s-%d", var.cluster_name, count.index + 1)}"
    cluster = "${var.cluster_name}"
  }
}

resource "aws_volume_attachment" "data_d" {
  device_name = "/dev/xvd${var.device_names["data"]}"
  count       = "${contains(keys(var.subnet_ids), "d") ? var.data_nodes_per_subnet : 0}"
  volume_id   = "${element(aws_ebs_volume.data_d.*.id, count.index)}"
  instance_id = "${element(aws_instance.data_d.*.id, (count.index / var.data_nodes_per_subnet))}"
}
  resource "aws_ebs_volume" "logs_d" {
  availability_zone = "${var.region}d"
  count             = "${contains(keys(var.subnet_ids), "d") ? var.data_nodes_per_subnet : 0}"
  size              = "${var.logs_storage_gb}"
  type              = "${var.storage_type}"

  tags = {
    Name = "${format("elasticsearch-data_d-logs-%s-%d", var.cluster_name, count.index + 1)}"
    cluster = "${var.cluster_name}"
  }
}

resource "aws_volume_attachment" "logs_d" {
  device_name = "/dev/xvd${var.device_names["logs"]}"
  count       = "${contains(keys(var.subnet_ids), "d") ? var.data_nodes_per_subnet : 0}"
  volume_id   = "${element(aws_ebs_volume.logs_d.*.id, count.index)}"
  instance_id = "${element(aws_instance.data_d.*.id, (count.index / var.data_nodes_per_subnet))}"
}
    resource "aws_ebs_volume" "data_e" {
  availability_zone = "${var.region}e"
  count             = "${contains(keys(var.subnet_ids), "e") ? var.data_nodes_per_subnet : 0}"
  size              = "${var.data_storage_gb}"
  type              = "${var.storage_type}"

  tags = {
    Name = "${format("elasticsearch-data_e-data-%s-%d", var.cluster_name, count.index + 1)}"
    cluster = "${var.cluster_name}"
  }
}

resource "aws_volume_attachment" "data_e" {
  device_name = "/dev/xvd${var.device_names["data"]}"
  count       = "${contains(keys(var.subnet_ids), "e") ? var.data_nodes_per_subnet : 0}"
  volume_id   = "${element(aws_ebs_volume.data_e.*.id, count.index)}"
  instance_id = "${element(aws_instance.data_e.*.id, (count.index / var.data_nodes_per_subnet))}"
}
  resource "aws_ebs_volume" "logs_e" {
  availability_zone = "${var.region}e"
  count             = "${contains(keys(var.subnet_ids), "e") ? var.data_nodes_per_subnet : 0}"
  size              = "${var.logs_storage_gb}"
  type              = "${var.storage_type}"

  tags = {
    Name = "${format("elasticsearch-data_e-logs-%s-%d", var.cluster_name, count.index + 1)}"
    cluster = "${var.cluster_name}"
  }
}

resource "aws_volume_attachment" "logs_e" {
  device_name = "/dev/xvd${var.device_names["logs"]}"
  count       = "${contains(keys(var.subnet_ids), "e") ? var.data_nodes_per_subnet : 0}"
  volume_id   = "${element(aws_ebs_volume.logs_e.*.id, count.index)}"
  instance_id = "${element(aws_instance.data_e.*.id, (count.index / var.data_nodes_per_subnet))}"
}
  